# version: '3'
# services:
#   backend:
#     build:
#       context: ./FastApp-Backend
#     container_name: backend
#     ports:
#       - "4000:4000"
#     depends_on:
#       - redis
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#     networks:
#       - app-network

#   frontend:
#     build:
#       context: ./FastApp-Frontend
#     container_name: frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   redis:
#     image: "redis:alpine"
#     container_name: redis
#     ports:
#       - "6380:6379"
#     volumes:
#       - redis-data:/data
#     networks:
#       - app-network

# volumes:
#   redis-data:

# networks:
#   app-network:
#     driver: bridge
